"""empty message

Revision ID: 70a3806679c0
Revises: 9f5d273822c4
Create Date: 2022-02-16 11:40:15.720688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a3806679c0'
down_revision = '9f5d273822c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'character', ['character_id'])
    op.create_unique_constraint(None, 'planet', ['planet_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planet', type_='unique')
    op.drop_constraint(None, 'character', type_='unique')
    # ### end Alembic commands ###
