"""empty message

Revision ID: 9f5d273822c4
Revises: f631efd4af14
Create Date: 2022-02-15 15:23:53.564608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f5d273822c4'
down_revision = 'f631efd4af14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'favoriteplanet', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'favoriteplanet', 'planet', ['planet_id'], ['planet_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favoriteplanet', type_='foreignkey')
    op.drop_constraint(None, 'favoriteplanet', type_='foreignkey')
    # ### end Alembic commands ###
